name: Run Antipattern Detection

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run-detection:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Increase timeout (e.g., 2 hours)

    steps:
      - name: Checkout This Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Ensure repos Directory Exists
        run: mkdir -p repos

      - name: Set PYTHONPATH to include detection directory
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/detection" >> $GITHUB_ENV

      - name: Run Detection on All Repositories
        run: python scripts/run_all.py  

      - name: Cleanup Cloned Repositories
        if: always()
        run: rm -rf repos  # Deletes all cloned repositories

      - name: Upload Misuse Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: misuses-report
          path: misuses_report.xlsx
      - name: Time and Misuse Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: final_report
          path: final_report.xlsx
